{{ config(
    materialized='view',
    schema='SEM'
) }}

SELECT
    MOVIE_ID,
    TITLE,
    GENRE,
    LANGUAGE,
    CERTIFICATION,
    RELEASE_TYPE,
    IS_FRANCHISE,
    STUDIO_NAME,

    COUNT(DISTINCT BOXOFFICE_ID) AS SHOW_COUNT,
    SUM(SCREENS) AS TOTAL_SCREENS,
    SUM(TICKETS_SOLD) AS TOTAL_TICKETS_SOLD,
    SUM(GROSS_LAKHS) AS TOTAL_GROSS_LAKHS,
    AVG(AVG_TICKET_PRICE) AS AVG_TICKET_PRICE,
    AVG(OCCUPANCY_RATE) AS AVG_OCCUPANCY_RATE

FROM {{ ref('v_boxoffice_analytics') }}

GROUP BY
    MOVIE_ID,
    TITLE,
    GENRE,
    LANGUAGE,
    CERTIFICATION,
    RELEASE_TYPE,
    IS_FRANCHISE,
    STUDIO_NAME