CREATE WAREHOUSE IF NOT EXISTS MOVIE_ANALYTICS_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE MOVIE_ANALYTICS_WH;

SHOW WAREHOUSES LIKE 'MOVIE_ANALYTICS_WH';