USE DATABASE MOVIE_ANALYTICS;
USE SCHEMA BRONZE;

CREATE OR REPLACE STAGE S3_MOVIE_STAGE
    URL = 's3://movie-analytics-sumanth-2026/landing/movie_analytics/'
    CREDENTIALS = (
        AWS_KEY_ID = 'YOUR_ACCESS_KEY_ID'
        AWS_SECRET_KEY = 'YOUR_SECRET_ACCESS_KEY'
    );

LIST @S3_MOVIE_STAGE;