USE DATABASE MOVIE_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS OPS;

CREATE OR REPLACE TABLE OPS.LOAD_AUDIT (
    AUDIT_ID        NUMBER AUTOINCREMENT,
    ENTITY_NAME     VARCHAR(100),
    FILE_NAME       VARCHAR(500),
    LOAD_START_TS   TIMESTAMP_NTZ,
    LOAD_END_TS     TIMESTAMP_NTZ,
    ROW_COUNT       NUMBER,
    STATUS          VARCHAR(30),
    ERROR_MESSAGE   VARCHAR(1000),
    BATCH_ID        VARCHAR(100)
);

CREATE OR REPLACE TABLE OPS.REJECTS (
    REJECT_ID       NUMBER AUTOINCREMENT,
    ENTITY_NAME     VARCHAR(100),
    FILE_NAME       VARCHAR(500),
    ROW_NUMBER      NUMBER,
    REJECT_REASON   VARCHAR(1000),
    REJECTED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID        VARCHAR(100)
);

SHOW TABLES IN SCHEMA MOVIE_ANALYTICS.OPS;
