USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS ROLE_ADMIN;
CREATE ROLE IF NOT EXISTS ROLE_INGEST;
CREATE ROLE IF NOT EXISTS ROLE_ETL;
CREATE ROLE IF NOT EXISTS ROLE_ANALYST;
CREATE ROLE IF NOT EXISTS ROLE_APP_STREAMLIT;
SHOW ROLES;


-- =========================================================
-- DATABASE / SCHEMA ACCESS
-- =========================================================

GRANT USAGE ON DATABASE MOVIE_ANALYTICS
TO ROLE ROLE_INGEST;

GRANT USAGE ON DATABASE MOVIE_ANALYTICS
TO ROLE ROLE_ETL;

GRANT USAGE ON DATABASE MOVIE_ANALYTICS
TO ROLE ROLE_ANALYST;

GRANT USAGE ON DATABASE MOVIE_ANALYTICS
TO ROLE ROLE_APP_STREAMLIT;


-- =========================================================
-- INGEST ROLE
-- Can load/read Bronze data
-- =========================================================

GRANT USAGE ON SCHEMA MOVIE_ANALYTICS.BRONZE
TO ROLE ROLE_INGEST;

GRANT INSERT, SELECT ON ALL TABLES
IN SCHEMA MOVIE_ANALYTICS.BRONZE
TO ROLE ROLE_INGEST;


-- =========================================================
-- ETL ROLE
-- Can read Bronze and manage transformation layers
-- =========================================================

GRANT USAGE ON SCHEMA MOVIE_ANALYTICS.BRONZE
TO ROLE ROLE_ETL;

GRANT SELECT ON ALL TABLES
IN SCHEMA MOVIE_ANALYTICS.BRONZE
TO ROLE ROLE_ETL;

GRANT USAGE ON SCHEMA MOVIE_ANALYTICS.SILVER
TO ROLE ROLE_ETL;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA MOVIE_ANALYTICS.SILVER
TO ROLE ROLE_ETL;

GRANT USAGE ON SCHEMA MOVIE_ANALYTICS.GOLD
TO ROLE ROLE_ETL;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA MOVIE_ANALYTICS.GOLD
TO ROLE ROLE_ETL;


-- =========================================================
-- ANALYST ROLE
-- Semantic layer only
-- =========================================================

GRANT USAGE ON SCHEMA MOVIE_ANALYTICS.SEM
TO ROLE ROLE_ANALYST;

GRANT SELECT ON ALL VIEWS
IN SCHEMA MOVIE_ANALYTICS.SEM
TO ROLE ROLE_ANALYST;


-- =========================================================
-- STREAMLIT ROLE
-- Semantic layer only
-- =========================================================

GRANT USAGE ON SCHEMA MOVIE_ANALYTICS.SEM
TO ROLE ROLE_APP_STREAMLIT;

GRANT SELECT ON ALL VIEWS
IN SCHEMA MOVIE_ANALYTICS.SEM
TO ROLE ROLE_APP_STREAMLIT;

GRANT SELECT ON FUTURE VIEWS
IN SCHEMA MOVIE_ANALYTICS.SEM
TO ROLE ROLE_ANALYST;

GRANT SELECT ON FUTURE VIEWS
IN SCHEMA MOVIE_ANALYTICS.SEM
TO ROLE ROLE_APP_STREAMLIT

SHOW ROLES LIKE 'ROLE_%';

-- DATABASE ACCESS

GRANT USAGE ON DATABASE MOVIE_ANALYTICS
TO ROLE ROLE_INGEST;

GRANT USAGE ON DATABASE MOVIE_ANALYTICS
TO ROLE ROLE_ETL;

GRANT USAGE ON DATABASE MOVIE_ANALYTICS
TO ROLE ROLE_ANALYST;

GRANT USAGE ON DATABASE MOVIE_ANALYTICS
TO ROLE ROLE_APP_STREAMLIT;


-- INGEST ROLE

GRANT USAGE ON SCHEMA MOVIE_ANALYTICS.BRONZE
TO ROLE ROLE_INGEST;

GRANT SELECT, INSERT ON ALL TABLES
IN SCHEMA MOVIE_ANALYTICS.BRONZE
TO ROLE ROLE_INGEST;


-- ETL ROLE

GRANT USAGE ON SCHEMA MOVIE_ANALYTICS.BRONZE
TO ROLE ROLE_ETL;

GRANT SELECT ON ALL TABLES
IN SCHEMA MOVIE_ANALYTICS.BRONZE
TO ROLE ROLE_ETL;

GRANT USAGE ON SCHEMA MOVIE_ANALYTICS.SILVER
TO ROLE ROLE_ETL;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA MOVIE_ANALYTICS.SILVER
TO ROLE ROLE_ETL;

GRANT USAGE ON SCHEMA MOVIE_ANALYTICS.GOLD
TO ROLE ROLE_ETL;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA MOVIE_ANALYTICS.GOLD
TO ROLE ROLE_ETL;


-- ANALYST ROLE
-- Access only to Semantic views

GRANT USAGE ON SCHEMA MOVIE_ANALYTICS.SEM
TO ROLE ROLE_ANALYST;

GRANT SELECT ON ALL VIEWS
IN SCHEMA MOVIE_ANALYTICS.SEM
TO ROLE ROLE_ANALYST;


-- STREAMLIT ROLE
-- Access only to Semantic views

GRANT USAGE ON SCHEMA MOVIE_ANALYTICS.SEM
TO ROLE ROLE_APP_STREAMLIT;

GRANT SELECT ON ALL VIEWS
IN SCHEMA MOVIE_ANALYTICS.SEM
TO ROLE ROLE_APP_STREAMLIT;


-- FUTURE SEMANTIC VIEWS

GRANT SELECT ON FUTURE VIEWS
IN SCHEMA MOVIE_ANALYTICS.SEM
TO ROLE ROLE_ANALYST;

GRANT SELECT ON FUTURE VIEWS
IN SCHEMA MOVIE_ANALYTICS.SEM
TO ROLE ROLE_APP_STREAMLIT;



SHOW GRANTS TO ROLE ROLE_APP_STREAMLIT;
SHOW GRANTS TO ROLE ROLE_ANALYST;

USE ROLE ACCOUNTADMIN;

GRANT USAGE ON DATABASE MOVIE_ANALYTICS
TO ROLE ROLE_ANALYST;

GRANT USAGE ON SCHEMA MOVIE_ANALYTICS.SEM
TO ROLE ROLE_ANALYST;

GRANT SELECT ON ALL VIEWS
IN SCHEMA MOVIE_ANALYTICS.SEM
TO ROLE ROLE_ANALYST;

GRANT SELECT ON FUTURE VIEWS
IN SCHEMA MOVIE_ANALYTICS.SEM
TO ROLE ROLE_ANALYST;


