{{ config(
    materialized='table'
) }}

SELECT
    TRIM(BOXOFFICE_ID) AS BOXOFFICE_ID,
    SHOW_DATE,
    TRIM(MOVIE_ID) AS MOVIE_ID,
    TRIM(LOCATION_ID) AS LOCATION_ID,
    TRIM(CHANNEL) AS CHANNEL,
    TRIM(PLATFORM_NAME) AS PLATFORM_NAME,
    SCREENS,
    TICKETS_SOLD,
    AVG_TICKET_PRICE,
    GROSS_LAKHS,
    OCCUPANCY_RATE,
    UPDATED_AT
FROM {{ ref('stg_boxoffice') }}

WHERE BOXOFFICE_ID IS NOT NULL
  AND SHOW_DATE IS NOT NULL
  AND MOVIE_ID IS NOT NULL
  AND LOCATION_ID IS NOT NULL