{{ config(
    materialized='table'
) }}

SELECT
    TRIM(STUDIO_ID) AS STUDIO_ID,
    TRIM(STUDIO_NAME) AS STUDIO_NAME,
    TRIM(COUNTRY) AS COUNTRY,
    TRIM(HQ_CITY) AS HQ_CITY,
    TRIM(HQ_STATE) AS HQ_STATE,
    TRIM(SIZE_BAND) AS SIZE_BAND,
    TRIM(STATUS) AS STATUS,
    FOUNDED_DATE,
    UPDATED_AT
FROM {{ ref('stg_studios') }}

WHERE STUDIO_ID IS NOT NULL
  AND STUDIO_NAME IS NOT NULL