{{ config(
    materialized='table'
) }}

SELECT
    TRIM(MOVIE_ID) AS MOVIE_ID,
    TRIM(TITLE) AS TITLE,
    TRIM(STUDIO_ID) AS STUDIO_ID,
    RELEASE_DATE,
    TRIM(GENRE) AS GENRE,
    TRIM(LANGUAGE) AS LANGUAGE,
    RUNTIME_MIN,
    TRIM(CERTIFICATION) AS CERTIFICATION,
    TRIM(RELEASE_TYPE) AS RELEASE_TYPE,
    BUDGET_CR,
    CASE
        WHEN UPPER(TRIM(IS_FRANCHISE)) IN ('Y', 'YES', 'TRUE', '1')
            THEN TRUE
        ELSE FALSE
    END AS IS_FRANCHISE,
    TRIM(STATUS) AS STATUS,
    UPDATED_AT

FROM {{ ref('stg_movies') }}

WHERE MOVIE_ID IS NOT NULL
  AND TITLE IS NOT NULL