{{ config(
    materialized='table'
) }}

SELECT
    TRIM(LOCATION_ID) AS LOCATION_ID,
    TRIM(CITY) AS CITY,
    TRIM(STATE) AS STATE,
    TRIM(COUNTRY) AS COUNTRY,
    TRIM(REGION) AS REGION,
    TRIM(CURRENCY) AS CURRENCY,
    TRIM(TIMEZONE) AS TIMEZONE,
    TRIM(STATUS) AS STATUS,
    UPDATED_AT
FROM {{ ref('stg_locations') }}

WHERE LOCATION_ID IS NOT NULL
  AND CITY IS NOT NULL